- name: Installing ZSH
  become: true
  apt:
    pkg:
      - zsh
  tags:
    - install
    - zsh

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  tags:
    - install
    - zsh

- name: Adding zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags:
    - install
    - zsh

- name: Copy Zsh Run Command file (.zshrc)
  copy:
    src: config/.zshrc
    dest: ~/
  tags:
    - install
    - zsh

- name: Set default shell to ZSH
  become: true
  user:
    name: '{{ ansible_user }}'
    shell: /bin/zsh
  tags:
    - install
    - zsh

- name: Export ZSH variable
  lineinfile:
    path: ~/.zshrc
    insertafter: '^# Path to your oh-my-zsh installation.'
    line: 'export ZSH="/home/{{ ansible_user }}/.oh-my-zsh"'
  tags:
    - install
    - zsh
