- name: Download golang tar 
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "~"
    mode: 0440
  tags:
    - install
    - go

- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  become: yes
  tags:
  - install
  - go

- name: Extract the Go tarball
  unarchive:
    src: "/home/{{ ansible_user }}/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    copy: no
  become: yes
  tags:
    - install
    - go

- name: Create go directories in home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0775
  with_items:
  - "~/go"
  - "~/go/bin"
  tags:
    - install
    - go
    
- name: Modify .profile
  blockinfile:
    dest: "~/bobo_dev/.borisrc"
    block: |
      export GOPATH=$HOME/go
      export GOBIN=$GOPATH/bin
      export PATH=$GOBIN:$PATH:/usr/local/go/bin
    marker: '# {mark} ANSIBLE MANAGED BLOCK - changes for golang'
    insertafter: EOF
    create: yes
  tags:
    - install
    - go

- name: Remove the Go Tar
  file:
    path: ~/go{{ go_version }}.linux-amd64.tar.gz
    state: absent
  tags:
    - install
    - go
